#!/bin/python
import random
import argparse
import linecache


def check(arg, letter, list):
    list[0] = '*'
    for i in range(len(arg)):
        if arg[i] == letter:
            list.append(i)
            list[0] = '!'
    return list

#komentarz
def encryption(arg,list):
    ret=[]
    for i in range(len(arg)):
        if list.count(i)>0:
            ret.append(arg[i])
        elif arg[i] != ' ':
            ret.append('_')
        elif arg[i] == ' ':
            ret.append(' ')
    return ret

def game(arg):
    gallows = ["""             _ 
            |/  
            |  
            |
            |  
            | 
            |
            | """,
            """             _ _ _ _
            |/ 
            |  
            |  
            |
            | 
            |
            | """,
            """             _ _ _ _
            |/  |
            |  (_)
            |  
            |
            | 
            |
            | """,
            """             _ _ _ _
            |/  |
            |  (_)
            |  \|/
            |   |
            |  /|
            |
            | """]
    wordknow=""
    words1 = ("china", "technology", "darkness")
    words2 = ("queue", "gallows", "encryption")
    words3 = ("establishment", "honorableness", "vet")
    words = [words1, words2, words3]
    if arg.file != None:
        try:
            file = open(arg.file, 'rU')
        except FileNotFoundError:
            print("File not found")
            return 1
        finally:
            file = open(arg.file, 'rU')
            max = len(file.readlines())
            num = random.randint(0, max)
            temp = linecache.getline(arg.plik, num)
            word = temp.rstrip('\n')
            file.close()

    else:
        word=random.choice(words[(arg.level-1)])
    listofknow = ['!']
    wordknow=encryption(word, listofknow)
    continuat=True
    miss=3
    while (continuat and (miss>0)):
        print(gallows[3 - miss])
        print(' '.join(wordknow))
        lit = input("Enter the letter (only small):")
        listofknow = check(word, lit, listofknow)
        wordknow = encryption(word, listofknow)
        continuat = False
        for i in range(len(word)):
            if word[i] != wordknow[i]:
                continuat = True
        if listofknow[0] == '*':
            miss -= 1
    if miss == 0:
        print(gallows[3])
        print(' '.join(word))
        print("You lose")
    else:
        print(gallows[3 - miss])
        print(' '.join(wordknow))
        print("Congratulations you won")
    return 0

parser = argparse.ArgumentParser()
parser.add_argument('--level', default=1, type=int, choices=range(1, 4))
parser.add_argument('--file', type=str)
# arg = parser.parse_args()
game(parser.parse_args())